import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { GoogleAnalytics } from '@/components/GoogleAnalytics'

const urbanist = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Jaimie Hemmings- Creative Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-slate-900 text-slate-100">
      <body className={`${urbanist.className} h-full relative`}>
        <GoogleAnalytics />
        <Header />
        {children}
        <div className="background-gradient inset-0 -z-50 min-h-screen top-0 fixed" />
        <div className="pointer-events-none inset-0 -z-40 h-screen bg-[url('/image/noisetexture.jpg')] background-repeat opacity-20 mix-blend-soft-light fixed w-full top-0 left-0"></div>
        <Footer />
      </body>
    </html>
  )
}
